name: CI

on: [ push, pull_request ]

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      CTEST_PARALLEL_LEVEL: 2
      WORKING_DIR: .

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-22.04-gcc-13
            os: ubuntu-22.04
            compiler: gcc
            version: "13"

          - name: ubuntu-22.04-clang-15
            os: ubuntu-22.04
            compiler: clang
            version: "15"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install
        run: |
          python -m pip install cmake==3.27.7 conan==2.0.13 --upgrade
          conan remote add conancenter https://center.conan.io --force
          sudo apt update
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          else
            sudo apt-get install -y clang-${{ matrix.version }} g++-multilib
            echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
          fi

          sudo apt install ninja-build

          git clone --depth=1 https://github.com/flutter/flutter.git
          echo "FLUTTER_HOME=${{ github.workspace }}/flutter" >> $GITHUB_ENV
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          conan profile detect
          cmake --preset Debug
          cmake --build --preset Debug
      - name: Test
        run: |
          ctest --preset Debug
