---
name: CI

on: [push, pull_request]

jobs:
    ci:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}

        env:
            CTEST_OUTPUT_ON_FAILURE: ON
            CTEST_PARALLEL_LEVEL: 2
            WORKING_DIR: .

        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: ubuntu-24.04-gcc-14
                      os: ubuntu-24.04
                      compiler: gcc
                      version: '14'

                    - name: ubuntu-24.04-clang-17
                      os: ubuntu-24.04
                      compiler: clang
                      version: '17'

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.11'
            - name: Install CI tools
              run: |
                  pip install pre-commit==3.6.0

                  # Install dart from flutter
                  git clone --depth=1 -b 3.16.9 https://github.com/flutter/flutter.git
                  echo "FLUTTER_HOME=${{ github.workspace }}/flutter" >> $GITHUB_ENV
                  echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
            - name: Run pre-commit
              run: pre-commit run --all-files
            - name: Install C++ dependencies
              run: |
                  python -m pip install cmake==3.31.6 --upgrade
                  sudo apt update
                  if [ "${{ matrix.compiler }}" = "gcc" ]; then
                    sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
                    echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
                    echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
                  else
                    wget https://apt.llvm.org/llvm.sh
                    chmod u+x llvm.sh
                    sudo ./llvm.sh ${{ matrix.version }}
                    echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
                    echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
                  fi

                  sudo apt install ninja-build
            - name: Build
              run: |
                  cmake --preset Debug
                  cmake --build --preset Debug
            - name: Test
              run: |
                  ctest --preset Debug
